// This file is part of VecSIMD
// Copyright (c) 2026 Marek Zalewski aka Drwalin, generated by LLM
// You should have received a copy of the MIT License along with this program.

#pragma once
#include "Aabb.hpp"

namespace simd
{

inline uint4 aabb4::IsValid() const
{
	return (min.x <= max.x) & (min.y <= max.y) & (min.z <= max.z);
}

inline float4 aabb4::GetVolume() const
{
	return GetSizes().x * GetSizes().y * GetSizes().z;
}
inline float4 aabb4::GetSurface() const
{
	vec3f size = GetSizes();
	return (size.x * size.y + size.x * size.z + size.y * size.z) *
		   float4::load(2.0f);
}

inline vec3f aabb4::GetCenter() const
{
	return (min + max) / float4::load(2.0f);
}
inline vec3f aabb4::GetSizes() const { return max - min; }
inline vec3f aabb4::GetMin() const { return min; }
inline vec3f aabb4::GetMax() const { return max; }

inline aabb4 aabb4::Expanded(float by) const
{
	float4 amount = float4::load(by);
	return {min - amount, max + amount};
}

inline uint4 aabb4::HasIntersection(const aabb4 &r) const
{
	return (max.x >= r.min.x) & (r.max.x >= min.x) & (max.y >= r.min.y) &
		   (r.max.y >= min.y) & (max.z >= r.min.z) & (r.max.z >= min.z);
}
inline uint4 aabb4::HasIntersection(const aabb4 &r, float eps) const
{
	return HasIntersection(r, float4::load(eps));
}
inline uint4 aabb4::HasIntersection(const aabb4 &r, float4 eps) const
{
	return (max.x + eps >= r.min.x) & (r.max.x + eps >= min.x) &
		   (max.y + eps >= r.min.y) & (r.max.y + eps >= min.y) &
		   (max.z + eps >= r.min.z) & (r.max.z + eps >= min.z);
}

inline uint4 aabb4::IsIn(const vec3f &r) const
{
	return (r.x >= min.x) & (r.x <= max.x) & (r.y >= min.y) & (r.y <= max.y) &
		   (r.z >= min.z) & (r.z <= max.z);
}
inline uint4 aabb4::IsIn(const vec3f &r, float eps) const
{
	return IsIn(r, float4::load(eps));
}
inline uint4 aabb4::IsIn(const vec3f &r, float4 eps) const
{
	return (r.x + eps >= min.x) & (r.x - eps <= max.x) & (r.y + eps >= min.y) &
		   (r.y - eps <= max.y) & (r.z + eps >= min.z) & (r.z - eps <= max.z);
}

inline aabb4 aabb4::Intersection(const aabb4 &r) const
{
	return {simd::max(min, r.min), simd::min(max, r.max)};
}

inline aabb4 aabb4::Sum(const aabb4 &r) const
{
	return {simd::min(min, r.min), simd::max(max, r.max)};
}
inline aabb4 aabb4::Sum(const vec3f &r) const
{
	return {simd::min(min, r), simd::max(max, r)};
}

inline uint4 aabb4::ContainsAll(const aabb4 &r) const
{
	return (min.x <= r.min.x) & (min.y <= r.min.y) & (min.z <= r.min.z) &
		   (max.x >= r.max.x) & (max.y >= r.max.y) & (max.z >= r.max.z);
}
inline uint4 aabb4::ContainsAll(const aabb4 &r, float eps) const
{
	return ContainsAll(r, float4::load(eps));
}
inline uint4 aabb4::ContainsAll(const aabb4 &r, float4 eps) const
{
	return (min.x <= r.min.x + eps) & (min.y <= r.min.y + eps) &
		   (min.z <= r.min.z + eps) & (max.x + eps >= r.max.x) &
		   (max.y + eps >= r.max.y) & (max.z + eps >= r.max.z);
}

inline aabb4 aabb4::GetChildRelativeAabb(aabb4 scaled_child) const
{
	vec3f new_min = min + (GetSizes() * scaled_child.min);
	vec3f new_max = new_min + ((max - new_min) * scaled_child.max);
	return {new_min, new_max};
}

inline uint4 aabb4::operator&&(const aabb4 &r) const
{
	return HasIntersection(r);
}
inline uint4 aabb4::operator&&(const vec3f &r) const { return IsIn(r); }

inline aabb4 aabb4::operator*(const aabb4 &r) const { return Intersection(r); }

inline aabb4 aabb4::operator+(const aabb4 &r) const { return Sum(r); }
inline aabb4 aabb4::operator+(const vec3f &r) const { return Sum(r); }

inline uint4 aabb4::operator==(const aabb4 &r) const
{
	return (min.x == r.min.x) & (min.y == r.min.y) & (min.z == r.min.z) &
		   (max.x == r.max.x) & (max.y == r.max.y) & (max.z == r.max.z);
}
inline uint4 aabb4::operator!=(const aabb4 &r) const
{
	return (min.x != r.min.x) | (min.y != r.min.y) | (min.z != r.min.z) |
		   (max.x != r.max.x) | (max.y != r.max.y) | (max.z != r.max.z);
}

} // namespace simd
