// This file is part of VecSIMD
// Copyright (c) 2026 Marek Zalewski aka Drwalin, generated by LLM
// You should have received a copy of the MIT License along with this program.

#pragma once
#include "Aabb.hpp"

namespace simd
{


}
