// This file is part of VecSIMD
// Copyright (c) 2026 Marek Zalewski aka Drwalin, generated by LLM
// You should have received a copy of the MIT License along with this program.

#pragma once

#include <stdint.h>

#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) ||             \
	defined(_M_IX86)

#if !defined(__SSE2__) && !(defined(_M_IX86_FP) && _M_IX86_FP >= 2)
#error vec128.h requires SSE2
#endif

#include <emmintrin.h>
#if defined(__SSE4_1__) || defined(_MSC_VER)
#include <smmintrin.h>
#endif
#if defined(__AVX512F__)
#include <immintrin.h>
#endif

typedef __m128 VECF;
typedef __m128i VECI;
typedef __m128i VECU;

#define VEC_F2U(v) _mm_castps_si128(v)
#define VEC_I2U(v) (v)
#define VEC_U2I(v) (v)

#define VEC_LOAD_F(p) _mm_load_ps((const float *)(p))
#define VEC_LOAD_I(p) _mm_load_si128((const __m128i *)(p))
#define VEC_LOAD_U(p) _mm_load_si128((const __m128i *)(p))
#define VEC_LOAD4B_I(p) _mm_loadu_si32(p)
#define VEC_LOAD4B_U(p) _mm_loadu_si32(p)
#define VEC_LOAD8B_I(p) _mm_loadu_si64(p)
#define VEC_LOAD8B_U(p) _mm_loadu_si64(p)
#define VEC_STORE_F(p, v) _mm_store_ps((float *)(p), (v))

#define VEC_SET1_F(v) _mm_set1_ps(v)
#define VEC_SET_F(v0, v1, v2, v3) _mm_setr_ps((v0), (v1), (v2), (v3))

// Widen 4 int8/uint8 values to int32/uint32 lanes.
#if defined(__SSE4_1__) || defined(_MSC_VER)
#define VEC_BI_TO_I(v) _mm_cvtepi8_epi32(v)
#define VEC_BU_TO_U(v) _mm_cvtepu8_epi32(v)
#else
#define _VEC_B2I(v)                                                            \
	_mm_srai_epi32(                                                            \
		_mm_unpacklo_epi16(_mm_srai_epi16(_mm_unpacklo_epi8((v), (v)), 8),     \
						   _mm_srai_epi16(_mm_unpacklo_epi8((v), (v)), 8)),    \
		16)
#define _VEC_B2U(v)                                                            \
	_mm_srli_epi32(                                                            \
		_mm_unpacklo_epi16(_mm_srli_epi16(_mm_unpacklo_epi8((v), (v)), 8),     \
						   _mm_srli_epi16(_mm_unpacklo_epi8((v), (v)), 8)),    \
		16)
#define VEC_BI_TO_I(v) _VEC_B2I(v)
#define VEC_BU_TO_U(v) _VEC_B2U(v)
#endif

// Widen 4 int16/uint16 values to int32/uint32 lanes.
#if defined(__SSE4_1__) || defined(_MSC_VER)
#define VEC_BI16_TO_I(p)                                                       \
	_mm_cvtepi16_epi32(p)
#define VEC_BU16_TO_U(p) _mm_cvtepu16_epi32(p)
#else
#define VEC_BI16_TO_I(v)                                                       \
	_mm_srai_epi32(_mm_unpacklo_epi16((v), (v)),                                \
								   16)
#define VEC_BU16_TO_U(v)                                                       \
	_mm_unpacklo_epi16((v),                                                       \
									   _mm_setzero_si128())
#endif

#define VEC_ITOF(v) _mm_cvtepi32_ps(v)

#define VEC_ADD_F(a, b) _mm_add_ps((a), (b))
#define VEC_SUB_F(a, b) _mm_sub_ps((a), (b))
#define VEC_MUL_F(a, b) _mm_mul_ps((a), (b))
#define VEC_DIV_F(a, b) _mm_div_ps((a), (b))
#define VEC_SQRT_F(a) _mm_sqrt_ps((a))
#define VEC_MIN_F(a, b) _mm_min_ps((a), (b))
#define VEC_MAX_F(a, b) _mm_max_ps((a), (b))
#if defined(__SSE4_1__) || defined(_MSC_VER)
#define VEC_ROUND_NEAREST_F(a) _mm_round_ps((a), _MM_FROUND_TO_NEAREST_INT | _MM_FROUND_NO_EXC)
#define VEC_FLOOR_F(a) _mm_round_ps((a), _MM_FROUND_TO_NEG_INF | _MM_FROUND_NO_EXC)
#define VEC_CEIL_F(a) _mm_round_ps((a), _MM_FROUND_TO_POS_INF | _MM_FROUND_NO_EXC)
#define VEC_ROUND_ZERO_F(a) _mm_round_ps((a), _MM_FROUND_TO_ZERO | _MM_FROUND_NO_EXC)
#else
#define VEC_ROUND_ZERO_F(a) _mm_cvtepi32_ps(_mm_cvttps_epi32(a))
#define VEC_ROUND_NEAREST_F(a) _mm_cvtepi32_ps(_mm_cvtps_epi32(a))
#define VEC_FLOOR_F(a)                                                         \
	_mm_sub_ps(VEC_ROUND_ZERO_F(a),                                      \
		_mm_and_ps(_mm_cmpgt_ps(VEC_ROUND_ZERO_F(a), (a)), _mm_set1_ps(1.0f)))
#define VEC_CEIL_F(a)                                                          \
	_mm_add_ps(VEC_ROUND_ZERO_F(a),                                      \
		_mm_and_ps(_mm_cmplt_ps(VEC_ROUND_ZERO_F(a), (a)), _mm_set1_ps(1.0f)))
#endif
#define VEC_ADD_I(a, b) _mm_add_epi32((a), (b))
#define VEC_SUB_I(a, b) _mm_sub_epi32((a), (b))
#define VEC_ADD_U(a, b) _mm_add_epi32((a), (b))
#define VEC_SUB_U(a, b) _mm_sub_epi32((a), (b))
#if defined(__SSE4_1__) || defined(_MSC_VER)
#define VEC_MUL_I(a, b) _mm_mullo_epi32((a), (b))
#define VEC_MUL_U(a, b) _mm_mullo_epi32((a), (b))
#define VEC_MIN_I(a, b) _mm_min_epi32((a), (b))
#define VEC_MAX_I(a, b) _mm_max_epi32((a), (b))
#define VEC_MIN_U(a, b) _mm_min_epu32((a), (b))
#define VEC_MAX_U(a, b) _mm_max_epu32((a), (b))
#else
#define _VEC_MUL32(a, b)                                                       \
	_mm_castps_si128(_mm_shuffle_ps(                                           \
		_mm_castsi128_ps(                                                      \
			_mm_unpacklo_epi64(_mm_mul_epu32((a), (b)),                        \
							   _mm_mul_epu32(_mm_shuffle_epi32((a), 0xF5),     \
											 _mm_shuffle_epi32((b), 0xF5)))),  \
		_mm_castsi128_ps(                                                      \
			_mm_unpackhi_epi64(_mm_mul_epu32((a), (b)),                        \
							   _mm_mul_epu32(_mm_shuffle_epi32((a), 0xF5),     \
											 _mm_shuffle_epi32((b), 0xF5)))),  \
		_MM_SHUFFLE(2, 0, 2, 0)))
#define VEC_MUL_I(a, b) _VEC_MUL32((a), (b))
#define _VEC_SIGNBIT _mm_set1_epi32((int)0x80000000u)
#define _VEC_MIN_I(a, b)                                                       \
	_mm_or_si128(                                                               \
		_mm_and_si128(_mm_cmpgt_epi32((b), (a)), (a)),                            \
		_mm_andnot_si128(_mm_cmpgt_epi32((b), (a)), (b)))
#define _VEC_MAX_I(a, b)                                                       \
	_mm_or_si128(                                                               \
		_mm_and_si128(_mm_cmpgt_epi32((a), (b)), (a)),                            \
		_mm_andnot_si128(_mm_cmpgt_epi32((a), (b)), (b)))
#define _VEC_MIN_U(a, b)                                                       \
	_mm_or_si128(                                                               \
		_mm_and_si128(                                                            \
			_mm_cmpgt_epi32(_mm_xor_si128((b), _VEC_SIGNBIT),                     \
				_mm_xor_si128((a), _VEC_SIGNBIT)),                                   \
			(a)),                                                                    \
		_mm_andnot_si128(                                                         \
			_mm_cmpgt_epi32(_mm_xor_si128((b), _VEC_SIGNBIT),                     \
				_mm_xor_si128((a), _VEC_SIGNBIT)),                                   \
			(b)))
#define _VEC_MAX_U(a, b)                                                       \
	_mm_or_si128(                                                               \
		_mm_and_si128(                                                            \
			_mm_cmpgt_epi32(_mm_xor_si128((a), _VEC_SIGNBIT),                     \
				_mm_xor_si128((b), _VEC_SIGNBIT)),                                   \
			(a)),                                                                    \
		_mm_andnot_si128(                                                         \
			_mm_cmpgt_epi32(_mm_xor_si128((a), _VEC_SIGNBIT),                     \
				_mm_xor_si128((b), _VEC_SIGNBIT)),                                   \
			(b)))
#define VEC_MIN_I(a, b) _VEC_MIN_I((a), (b))
#define VEC_MAX_I(a, b) _VEC_MAX_I((a), (b))
#define VEC_MIN_U(a, b) _VEC_MIN_U((a), (b))
#define VEC_MAX_U(a, b) _VEC_MAX_U((a), (b))
#endif

#define _VEC_ONEI _mm_set1_epi32(-1)

#define VEC_CMP_EQ_F(a, b) _mm_cmpeq_ps((a), (b))
#define VEC_CMP_NE_F(a, b) _mm_cmpneq_ps((a), (b))
#define VEC_CMP_GT_F(a, b) _mm_cmpgt_ps((a), (b))
#define VEC_CMP_LT_F(a, b) _mm_cmplt_ps((a), (b))
#define VEC_CMP_GE_F(a, b) _mm_cmpge_ps((a), (b))
#define VEC_CMP_LE_F(a, b) _mm_cmple_ps((a), (b))
#define VEC_CMP_EQ_I(a, b) _mm_cmpeq_epi32((a), (b))
#define VEC_CMP_NE_I(a, b) _mm_xor_si128(_mm_cmpeq_epi32((a), (b)), _VEC_ONEI)
#define VEC_CMP_GT_I(a, b) _mm_cmpgt_epi32((a), (b))
#define VEC_CMP_LT_I(a, b) _mm_cmpgt_epi32((b), (a))
#define VEC_CMP_GE_I(a, b) _mm_xor_si128(_mm_cmpgt_epi32((b), (a)), _VEC_ONEI)
#define VEC_CMP_LE_I(a, b) _mm_xor_si128(_mm_cmpgt_epi32((a), (b)), _VEC_ONEI)
#define VEC_CMP_EQ_U(a, b) _mm_cmpeq_epi32((a), (b))
#define VEC_CMP_NE_U(a, b) _mm_xor_si128(_mm_cmpeq_epi32((a), (b)), _VEC_ONEI)
#define VEC_AND_I(a, b) _mm_and_si128((a), (b))
#define VEC_OR_I(a, b) _mm_or_si128((a), (b))
#define VEC_XOR_I(a, b) _mm_xor_si128((a), (b))
#define VEC_NOT_I(a) _mm_xor_si128((a), _VEC_ONEI)
#define VEC_AND_U(a, b) _mm_and_si128((a), (b))
#define VEC_OR_U(a, b) _mm_or_si128((a), (b))
#define VEC_XOR_U(a, b) _mm_xor_si128((a), (b))
#define VEC_NOT_U(a) _mm_xor_si128((a), _VEC_ONEI)

#define VEC_SHL_I(a, n) _mm_slli_epi32((a), (n))
#define VEC_SHR_I(a, n) _mm_srai_epi32((a), (n))
#define VEC_SHL_U(a, n) _mm_slli_epi32((a), (n))
#define VEC_SHR_U(a, n) _mm_srli_epi32((a), (n))
#define VEC_SHL_U_VAR(a, n) _mm_sll_epi32((a), _mm_cvtsi32_si128(n))
#define VEC_SHR_U_VAR(a, n) _mm_srl_epi32((a), _mm_cvtsi32_si128(n))

#elif defined(__aarch64__) || defined(_M_ARM64) || defined(__ARM_NEON) ||      \
	defined(__ARM_NEON__)

#if defined(_M_ARM64)
#include <arm64_neon.h>
#else
#include <arm_neon.h>
#endif

typedef float32x4_t VECF;
typedef int32x4_t VECI;
typedef uint32x4_t VECU;

#define VEC_F2U(v) vreinterpretq_u32_f32(v)
#define VEC_I2U(v) vreinterpretq_u32_s32(v)
#define VEC_U2I(v) vreinterpretq_s32_u32(v)

#define VEC_LOAD_F(p) vld1q_f32((const float32_t *)(p))
#define VEC_LOAD_I(p) vld1q_s32((const int32_t *)(p))
#define VEC_LOAD_U(p) vld1q_u32((const uint32_t *)(p))
#define VEC_LOAD4B_I(p) vdupq_n_s32(*(const int32_t *)(p))
#define VEC_LOAD4B_U(p) vdupq_n_u32(*(const uint32_t *)(p))
#define VEC_LOAD8B_I(p) vreinterpretq_s32_s64(vdupq_n_s64(*(const int64_t *)(p)))
#define VEC_LOAD8B_U(p) vreinterpretq_u32_u64(vdupq_n_u64(*(const uint64_t *)(p)))
#define VEC_STORE_F(p, v) vst1q_f32((float32_t *)(p), (v))

#define VEC_SET1_F(v) vdupq_n_f32(v)
#define VEC_SET_F(v0, v1, v2, v3)                                             \
	vsetq_lane_f32((v3), vsetq_lane_f32((v2), vsetq_lane_f32((v1),              \
		vsetq_lane_f32((v0), vdupq_n_f32(0.0f), 0), 1), 2), 3)

#define VEC_BI_TO_I(v)                                                         \
	vmovl_s16(vget_low_s16(vmovl_s8(vget_low_s8(vreinterpretq_s8_s32(v)))))
#define VEC_BU_TO_U(v)                                                         \
	vmovl_u16(vget_low_u16(vmovl_u8(vget_low_u8(vreinterpretq_u8_u32(v)))))

// Widen 4 int16/uint16 values to int32/uint32 lanes.
#define VEC_BI16_TO_I(v)                                                       \
	vmovl_s16(vget_low_s16(vreinterpretq_s16_s32(v)))
#define VEC_BU16_TO_U(v)                                                       \
	vmovl_u16(vget_low_u16(vreinterpretq_u16_u32(v)))

#define VEC_ITOF(v) vcvtq_f32_s32(v)

#define VEC_ADD_F(a, b) vaddq_f32((a), (b))
#define VEC_SUB_F(a, b) vsubq_f32((a), (b))
#define VEC_MUL_F(a, b) vmulq_f32((a), (b))
#if defined(__aarch64__)
#define VEC_DIV_F(a, b) vdivq_f32((a), (b))
#else
#define _VEC_RCP1(v) vmulq_f32(vrecpeq_f32(v), vrecpsq_f32(v, vrecpeq_f32(v)))
#define _VEC_RCP(v) vmulq_f32(_VEC_RCP1(v), vrecpsq_f32(v, _VEC_RCP1(v)))
#define VEC_DIV_F(a, b) vmulq_f32((a), _VEC_RCP(b))
#endif
#if defined(__aarch64__)
#define VEC_SQRT_F(a) vsqrtq_f32(a)
#define VEC_ROUND_NEAREST_F(a) vrndnq_f32(a)
#define VEC_FLOOR_F(a) vrndmq_f32(a)
#define VEC_CEIL_F(a) vrndpq_f32(a)
#define VEC_ROUND_ZERO_F(a) vrndq_f32(a)
#else
#define VEC_SQRT_F(a)                                                          \
	vmulq_f32((a), vrsqrteq_f32((a)))
#define VEC_ROUND_ZERO_F(a)                                                    \
	vcvtq_f32_s32(vcvtq_s32_f32(a))
#define VEC_ROUND_NEAREST_F(a)                                                  \
	vcvtq_f32_s32(vcvtq_s32_f32(vaddq_f32((a), vdupq_n_f32(0.5f))))
#define VEC_FLOOR_F(a)                                                         \
	vsubq_f32(VEC_ROUND_ZERO_F(a),                                               \
		vreinterpretq_f32_u32(vandq_u32(                                         \
			vcgtq_f32(VEC_ROUND_ZERO_F(a), (a)), vdupq_n_u32(0x3F800000))))
#define VEC_CEIL_F(a)                                                          \
	vaddq_f32(VEC_ROUND_ZERO_F(a),                                               \
		vreinterpretq_f32_u32(vandq_u32(                                         \
			vcltq_f32(VEC_ROUND_ZERO_F(a), (a)), vdupq_n_u32(0x3F800000))))
#endif
#define VEC_ADD_I(a, b) vaddq_s32((a), (b))
#define VEC_SUB_I(a, b) vsubq_s32((a), (b))
#define VEC_MUL_I(a, b) vmulq_s32((a), (b))
#define VEC_ADD_U(a, b) vaddq_u32((a), (b))
#define VEC_SUB_U(a, b) vsubq_u32((a), (b))
#define VEC_MUL_U(a, b) vmulq_u32((a), (b))
#define VEC_MIN_F(a, b) vminq_f32((a), (b))
#define VEC_MAX_F(a, b) vmaxq_f32((a), (b))
#define VEC_MIN_I(a, b) vminq_s32((a), (b))
#define VEC_MAX_I(a, b) vmaxq_s32((a), (b))
#define VEC_MIN_U(a, b) vminq_u32((a), (b))
#define VEC_MAX_U(a, b) vmaxq_u32((a), (b))

#define VEC_CMP_EQ_F(a, b) vreinterpretq_f32_u32(vceqq_f32((a), (b)))
#define VEC_CMP_NE_F(a, b) vreinterpretq_f32_u32(vmvnq_u32(vceqq_f32((a), (b))))
#define VEC_CMP_GT_F(a, b) vreinterpretq_f32_u32(vcgtq_f32((a), (b)))
#define VEC_CMP_LT_F(a, b) vreinterpretq_f32_u32(vcltq_f32((a), (b)))
#define VEC_CMP_GE_F(a, b) vreinterpretq_f32_u32(vcgeq_f32((a), (b)))
#define VEC_CMP_LE_F(a, b) vreinterpretq_f32_u32(vcleq_f32((a), (b)))
#define VEC_CMP_EQ_I(a, b) vceqq_s32((a), (b))
#define VEC_CMP_NE_I(a, b) vmvnq_s32(vceqq_s32((a), (b)))
#define VEC_CMP_GT_I(a, b) vcgtq_s32((a), (b))
#define VEC_CMP_LT_I(a, b) vcltq_s32((a), (b))
#define VEC_CMP_GE_I(a, b) vcgeq_s32((a), (b))
#define VEC_CMP_LE_I(a, b) vcleq_s32((a), (b))
#define VEC_CMP_EQ_U(a, b) vceqq_u32((a), (b))
#define VEC_CMP_NE_U(a, b) vmvnq_u32(vceqq_u32((a), (b)))
#define VEC_CMP_GT_U(a, b) vcgtq_u32((a), (b))
#define VEC_CMP_LT_U(a, b) vcltq_u32((a), (b))
#define VEC_CMP_GE_U(a, b) vcgeq_u32((a), (b))
#define VEC_CMP_LE_U(a, b) vcleq_u32((a), (b))
#define VEC_AND_I(a, b) vandq_s32((a), (b))
#define VEC_OR_I(a, b) vorrq_s32((a), (b))
#define VEC_XOR_I(a, b) veorq_s32((a), (b))
#define VEC_NOT_I(a) vmvnq_s32((a))
#define VEC_AND_U(a, b) vandq_u32((a), (b))
#define VEC_OR_U(a, b) vorrq_u32((a), (b))
#define VEC_XOR_U(a, b) veorq_u32((a), (b))
#define VEC_NOT_U(a) vmvnq_u32((a))

#define VEC_SHL_I(a, n) vshlq_n_s32((a), (n))
#define VEC_SHR_I(a, n) vshrq_n_s32((a), (n))
#define VEC_SHL_U(a, n) vshlq_n_u32((a), (n))
#define VEC_SHR_U(a, n) vshrq_n_u32((a), (n))
#define VEC_SHL_U_VAR(a, n) vshlq_u32((a), vdupq_n_s32(n))
#define VEC_SHR_U_VAR(a, n) vshlq_u32((a), vdupq_n_s32(-(n)))

#else
#error vec128.h requires SSE2 (x86) or NEON (ARM)
#endif
