// This file is part of VecSIMD
// Copyright (c) 2026 Marek Zalewski aka Drwalin, generated by LLM
// You should have received a copy of the MIT License along with this program.

#pragma once
#include "Vec3.hpp"

namespace simd
{

inline ubyte16 ubyte16::load(const void *v) { return {VEC_LOAD_U(v)}; }
inline byte16 byte16::load(const void *v) { return {VEC_LOAD_I(v)}; }

inline uword8 uword8::load(const void *v) { return {VEC_LOAD_U(v)}; }
inline word8 word8::load(const void *v) { return {VEC_LOAD_I(v)}; }

inline uint4 uint4::load(const void *v) { return {VEC_LOAD_U(v)}; }
inline uint4 uint4::convert_from(ubyte16 src) { return {VEC_BU_TO_U(src.v)}; }
inline uint4 uint4::convert_from(uword8 src) { return {VEC_BU16_TO_U(src.v)}; }
inline uint4 uint4::reinterpret(int4 src) { return {VEC_I2U(src.v)}; }

inline uint4 uint4::operator&(uint4 other) const
{
	return {VEC_AND_U(v, other.v)};
}
inline uint4 uint4::operator|(uint4 other) const
{
	return {VEC_OR_U(v, other.v)};
}
inline uint4 uint4::operator^(uint4 other) const
{
	return {VEC_XOR_U(v, other.v)};
}
inline uint4 uint4::operator~() const { return {VEC_NOT_U(v)}; }

inline uint4 uint4::operator<<(int bits) const
{
	return {VEC_SHL_U_VAR(v, bits)};
}
inline uint4 uint4::operator>>(int bits) const
{
	return {VEC_SHR_U_VAR(v, bits)};
}
template <int bits> inline uint4 uint4::shl() const
{
	static_assert(bits >= 0 && bits < 32,
				  "uint4 shift count must be in [0, 31]");
	return {VEC_SHL_U(v, bits)};
}
template <int bits> inline uint4 uint4::shr() const
{
	static_assert(bits >= 0 && bits < 32,
				  "uint4 shift count must be in [0, 31]");
	return {VEC_SHR_U(v, bits)};
}

inline int4 int4::load(const void *v) { return {VEC_LOAD_I(v)}; }
inline int4 int4::convert_from(byte16 src) { return {VEC_BI_TO_I(src.v)}; }
inline int4 int4::convert_from(word8 src) { return {VEC_BI16_TO_I(src.v)}; }
inline int4 int4::reinterpret(uint4 src) { return {VEC_U2I(src.v)}; }

inline int4 int4::operator+(int4 other) const
{
	return {VEC_ADD_I(v, other.v)};
}
inline int4 int4::operator-(int4 other) const
{
	return {VEC_SUB_I(v, other.v)};
}
inline int4 int4::operator*(int4 other) const
{
	return {VEC_MUL_I(v, other.v)};
}

inline float4 float4::load(const float *v) { return {VEC_LOAD_F(v)}; }
inline float4 float4::load(float v1, float v2, float v3, float v4)
{
	return {VEC_SET_F(v1, v2, v3, v4)};
}
inline float4 float4::load(float v) { return {VEC_SET1_F(v)}; }
inline float4 float4::convert_from(int4 src) { return {VEC_ITOF(src.v)}; }

inline void float4::store(float *v) const { VEC_STORE_F(v, this->v); }

inline float4 float4::operator-(int other) const
{
	return {VEC_SUB_F(v, VEC_SET1_F((float)other))};
}
inline float4 float4::operator+(float4 other) const
{
	return {VEC_ADD_F(v, other.v)};
}
inline float4 float4::operator-(float4 other) const
{
	return {VEC_SUB_F(v, other.v)};
}
inline float4 float4::operator*(float4 other) const
{
	return {VEC_MUL_F(v, other.v)};
}
inline float4 float4::operator/(float4 other) const
{
	return {VEC_DIV_F(v, other.v)};
}

inline float4 float4::sqrt() const { return {VEC_SQRT_F(v)}; }
inline float4 float4::round_to_nearest() const
{
	return {VEC_ROUND_NEAREST_F(v)};
}
inline float4 float4::floor() const { return {VEC_FLOOR_F(v)}; }
inline float4 float4::ceil() const { return {VEC_CEIL_F(v)}; }
inline float4 float4::round_to_zero() const { return {VEC_ROUND_ZERO_F(v)}; }

#define VEC_FLOAT4_CMP(method, macro)                                          \
	inline uint4 float4::method(float4 r) const                                \
	{                                                                          \
		return {VEC_F2U(macro(v, r.v))};                                       \
	}
VEC_FLOAT4_CMP(operator<, VEC_CMP_LT_F)
VEC_FLOAT4_CMP(operator>, VEC_CMP_GT_F)
VEC_FLOAT4_CMP(operator<=, VEC_CMP_LE_F)
VEC_FLOAT4_CMP(operator>=, VEC_CMP_GE_F)
VEC_FLOAT4_CMP(operator==, VEC_CMP_EQ_F)
VEC_FLOAT4_CMP(operator!=, VEC_CMP_NE_F)
#undef VEC_FLOAT4_CMP

inline vec3f vec3f::load(const float *x, const float *y, const float *z)
{
	return {float4::load(x), float4::load(y), float4::load(z)};
}
inline vec3f vec3f::load(float x, float y, float z)
{
	return {float4::load(x), float4::load(y), float4::load(z)};
}

inline void vec3f::store(float *x, float *y, float *z) const
{
	this->x.store(x);
	this->y.store(y);
	this->z.store(z);
}

inline vec3f vec3f::operator-(int other) const
{
	return {x - other, y - other, z - other};
}

inline vec3f vec3f::operator+(vec3f other) const
{
	return {x + other.x, y + other.y, z + other.z};
}
inline vec3f vec3f::operator-(vec3f other) const
{
	return {x - other.x, y - other.y, z - other.z};
}
inline vec3f vec3f::operator*(vec3f other) const
{
	return {x * other.x, y * other.y, z * other.z};
}
inline vec3f vec3f::operator/(vec3f other) const
{
	return {x / other.x, y / other.y, z / other.z};
}

inline vec3f vec3f::operator+(float4 other) const
{
	return {x + other, y + other, z + other};
}
inline vec3f vec3f::operator-(float4 other) const
{
	return {x - other, y - other, z - other};
}
inline vec3f vec3f::operator*(float4 other) const
{
	return {x * other, y * other, z * other};
}
inline vec3f vec3f::operator/(float4 other) const
{
	return {x / other, y / other, z / other};
}

inline float4 vec3f::dot(vec3f other) const
{
	return x * other.x + y * other.y + z * other.z;
}
inline vec3f vec3f::cross(vec3f other) const
{
	return {y * other.z - z * other.y, z * other.x - x * other.z,
			x * other.y - y * other.x};
}
inline float4 vec3f::length2() const { return dot(*this); }
inline float4 vec3f::length() const { return length2().sqrt(); }

} // namespace simd
